-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.chats
(
    message_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    user_id bigint NOT NULL,
    message text COLLATE pg_catalog."default",
    sent_at timestamp with time zone DEFAULT now(),
    game_id bigint,
    lobby_id character varying COLLATE pg_catalog."default",
    CONSTRAINT chats_pkey PRIMARY KEY (message_id),
    CONSTRAINT chats_check_one_parent CHECK (
        (game_id IS NOT NULL AND lobby_id IS NULL) OR 
        (game_id IS NULL AND lobby_id IS NOT NULL)
    )
);

CREATE TABLE IF NOT EXISTS public.game_details
(
    game_details_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    game_id bigint NOT NULL,
    user_id bigint NOT NULL,
    turn_order integer,
    score integer DEFAULT 0,
    CONSTRAINT game_details_pkey PRIMARY KEY (game_details_id)
);

CREATE TABLE IF NOT EXISTS public.games
(
    game_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    board_size smallint NOT NULL,
    winner_id bigint,
    current_turn bigint,
    name character varying COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT now(),
    ended_at timestamp with time zone,
    CONSTRAINT games_pkey PRIMARY KEY (game_id)
);

CREATE TABLE IF NOT EXISTS public.grids
(
    box_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    game_id bigint,
    top_edge boolean DEFAULT false,
    right_edge boolean DEFAULT false,
    left_edge boolean DEFAULT false,
    bottom_edge boolean DEFAULT false,
    grid_row smallint,
    grid_col smallint,
    completed boolean,
    completed_by bigint,
    CONSTRAINT grids_pkey PRIMARY KEY (box_id)
);



CREATE TABLE IF NOT EXISTS public.users
(
    user_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    username character varying COLLATE pg_catalog."default" NOT NULL,
    password character varying COLLATE pg_catalog."default",
    is_guest boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT now(),
    role character varying COLLATE pg_catalog."default",
    CONSTRAINT users_pkey PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS public.game_events
(
    event_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    game_id bigint NOT NULL,
    event_type character varying NOT NULL,
    version integer NOT NULL,
    payload jsonb NOT NULL,
    occurred_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT game_events_pkey PRIMARY KEY (event_id)
);

ALTER TABLE IF EXISTS public.chats

    ADD CONSTRAINT chats_game_id_fkey FOREIGN KEY (game_id)
    REFERENCES public.games (game_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.chats
    ADD CONSTRAINT chats_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;



ALTER TABLE IF EXISTS public.game_details
    ADD CONSTRAINT game_details_game_id_fkey FOREIGN KEY (game_id)
    REFERENCES public.games (game_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.game_details
    ADD CONSTRAINT game_details_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.games

    ADD CONSTRAINT games_winner_id_fkey FOREIGN KEY (winner_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;




ALTER TABLE IF EXISTS public.grids
    ADD CONSTRAINT grids_completed_by_fkey FOREIGN KEY (completed_by)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.grids
    ADD CONSTRAINT grids_game_id_fkey FOREIGN KEY (game_id)
    REFERENCES public.games (game_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.game_events
    ADD CONSTRAINT game_events_game_id_fkey FOREIGN KEY (game_id)
    REFERENCES public.games (game_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE
    NOT VALID;


END;