/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JoinLobbyIDRouteImport } from './routes/join.$lobbyID'
import { Route as GameGameIDRouteImport } from './routes/game/$gameID'
import { Route as AuthenticatedPlayRouteImport } from './routes/_authenticated/play'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedChooseNameRouteImport } from './routes/_authenticated/choose-name'
import { Route as AuthenticatedReplayGameIDRouteImport } from './routes/_authenticated/replay/$gameID'
import { Route as AuthenticatedLobbyLobbyIDRouteImport } from './routes/_authenticated/lobby/$lobbyID'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinLobbyIDRoute = JoinLobbyIDRouteImport.update({
  id: '/join/$lobbyID',
  path: '/join/$lobbyID',
  getParentRoute: () => rootRouteImport,
} as any)
const GameGameIDRoute = GameGameIDRouteImport.update({
  id: '/game/$gameID',
  path: '/game/$gameID',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPlayRoute = AuthenticatedPlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChooseNameRoute = AuthenticatedChooseNameRouteImport.update({
  id: '/choose-name',
  path: '/choose-name',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReplayGameIDRoute =
  AuthenticatedReplayGameIDRouteImport.update({
    id: '/replay/$gameID',
    path: '/replay/$gameID',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLobbyLobbyIDRoute =
  AuthenticatedLobbyLobbyIDRouteImport.update({
    id: '/lobby/$lobbyID',
    path: '/lobby/$lobbyID',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/choose-name': typeof AuthenticatedChooseNameRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/play': typeof AuthenticatedPlayRoute
  '/game/$gameID': typeof GameGameIDRoute
  '/join/$lobbyID': typeof JoinLobbyIDRoute
  '/lobby/$lobbyID': typeof AuthenticatedLobbyLobbyIDRoute
  '/replay/$gameID': typeof AuthenticatedReplayGameIDRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/choose-name': typeof AuthenticatedChooseNameRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/play': typeof AuthenticatedPlayRoute
  '/game/$gameID': typeof GameGameIDRoute
  '/join/$lobbyID': typeof JoinLobbyIDRoute
  '/lobby/$lobbyID': typeof AuthenticatedLobbyLobbyIDRoute
  '/replay/$gameID': typeof AuthenticatedReplayGameIDRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/choose-name': typeof AuthenticatedChooseNameRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/play': typeof AuthenticatedPlayRoute
  '/game/$gameID': typeof GameGameIDRoute
  '/join/$lobbyID': typeof JoinLobbyIDRoute
  '/_authenticated/lobby/$lobbyID': typeof AuthenticatedLobbyLobbyIDRoute
  '/_authenticated/replay/$gameID': typeof AuthenticatedReplayGameIDRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/leaderboard'
    | '/login'
    | '/register'
    | '/choose-name'
    | '/history'
    | '/play'
    | '/game/$gameID'
    | '/join/$lobbyID'
    | '/lobby/$lobbyID'
    | '/replay/$gameID'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/leaderboard'
    | '/login'
    | '/register'
    | '/choose-name'
    | '/history'
    | '/play'
    | '/game/$gameID'
    | '/join/$lobbyID'
    | '/lobby/$lobbyID'
    | '/replay/$gameID'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/leaderboard'
    | '/login'
    | '/register'
    | '/_authenticated/choose-name'
    | '/_authenticated/history'
    | '/_authenticated/play'
    | '/game/$gameID'
    | '/join/$lobbyID'
    | '/_authenticated/lobby/$lobbyID'
    | '/_authenticated/replay/$gameID'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  GameGameIDRoute: typeof GameGameIDRoute
  JoinLobbyIDRoute: typeof JoinLobbyIDRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$lobbyID': {
      id: '/join/$lobbyID'
      path: '/join/$lobbyID'
      fullPath: '/join/$lobbyID'
      preLoaderRoute: typeof JoinLobbyIDRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$gameID': {
      id: '/game/$gameID'
      path: '/game/$gameID'
      fullPath: '/game/$gameID'
      preLoaderRoute: typeof GameGameIDRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/play': {
      id: '/_authenticated/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof AuthenticatedPlayRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/choose-name': {
      id: '/_authenticated/choose-name'
      path: '/choose-name'
      fullPath: '/choose-name'
      preLoaderRoute: typeof AuthenticatedChooseNameRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/replay/$gameID': {
      id: '/_authenticated/replay/$gameID'
      path: '/replay/$gameID'
      fullPath: '/replay/$gameID'
      preLoaderRoute: typeof AuthenticatedReplayGameIDRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lobby/$lobbyID': {
      id: '/_authenticated/lobby/$lobbyID'
      path: '/lobby/$lobbyID'
      fullPath: '/lobby/$lobbyID'
      preLoaderRoute: typeof AuthenticatedLobbyLobbyIDRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedChooseNameRoute: typeof AuthenticatedChooseNameRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedPlayRoute: typeof AuthenticatedPlayRoute
  AuthenticatedLobbyLobbyIDRoute: typeof AuthenticatedLobbyLobbyIDRoute
  AuthenticatedReplayGameIDRoute: typeof AuthenticatedReplayGameIDRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedChooseNameRoute: AuthenticatedChooseNameRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedPlayRoute: AuthenticatedPlayRoute,
  AuthenticatedLobbyLobbyIDRoute: AuthenticatedLobbyLobbyIDRoute,
  AuthenticatedReplayGameIDRoute: AuthenticatedReplayGameIDRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  GameGameIDRoute: GameGameIDRoute,
  JoinLobbyIDRoute: JoinLobbyIDRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
